//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classify
    {
        public Classify()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ClassifyID { get; set; }
        public string ClassifyName { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
